FROM node:20-alpine
WORKDIR /app
COPY frontend/package.json ./
RUN npm i --no-audit --no-fund && npm i -g serve
COPY frontend .
RUN npm run build
ENV PORT=10000
EXPOSE 10000
CMD ["sh", "-c", "serve -s dist -l ${PORT}"]
