FROM node:20-alpine AS fe_build
WORKDIR /fe
COPY frontend/package.json ./package.json
RUN npm i --no-audit --no-fund
COPY frontend .
RUN npm run build

FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/app ./app
COPY --from=fe_build /fe/dist ./app/static
ENV PORT=10000
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"]
